#1. What is a Python library? Why ^o we use Python libraries?
A Python library is a collection of pre-written Python code that provides functionalities and tools to perform specific tasks or solve particular problems. These libraries are designed to be reusable and can be imported into Python scripts or programs to extend their capabilities without having to write code from scratch.

There are several reasons why we use Python libraries:

Reusability: Python libraries contain pre-written code that can be reused in different projects, saving time and effort. Instead of writing code to implement common functionalities, developers can leverage existing libraries.

Efficiency: Python libraries are typically optimized for performance and reliability. By using well-tested and optimized code from libraries, developers can build applications more efficiently and with fewer bugs.

Specialized Functionality: Python libraries often provide specialized functionalities for specific domains or tasks. For example, there are libraries for data analysis, machine learning, web development, image processing, and more. These libraries offer ready-made solutions tailored to particular needs.

Community Support: Many Python libraries are open-source and have active communities of developers contributing to their development and maintenance. This means that users can benefit from community support, documentation, tutorials, and updates to the libraries over time.

Interoperability: Python libraries are designed to work well with other Python code and external systems. They often provide interfaces and APIs for interacting with external services, databases, file formats, and other software components.

Overall, Python libraries play a crucial role in extending the capabilities of the Python programming language, making it a versatile and powerful tool for a wide range of applications and domains.

#2. What is the ^ifference between Numpy array an^ List?
The difference between NumPy arrays and Python lists lies primarily in their underlying implementation, functionality, and performance characteristics. Here's a comparison between NumPy arrays and Python lists:

Data Structure:

NumPy Array: NumPy arrays are homogeneous data structures, meaning they contain elements of the same data type. NumPy arrays are implemented in C and provide a contiguous block of memory, which allows for efficient computation and vectorized operations.
Python List: Python lists are heterogeneous data structures, meaning they can contain elements of different data types. Lists are implemented as dynamic arrays in Python, allowing for flexible resizing and mixed data types.
Performance:

NumPy Array: NumPy arrays are optimized for numerical computations and vectorized operations. They are more memory-efficient and faster than Python lists, especially for large datasets and numerical computations involving array operations.
Python List: Python lists are more flexible but less efficient in terms of memory usage and performance compared to NumPy arrays. Iterating over Python lists or performing operations on each element individually can be slower than using NumPy arrays.
Functionality:

NumPy Array: NumPy arrays provide a wide range of mathematical functions and operations for numerical computing, such as element-wise arithmetic operations, linear algebra, statistical functions, and more. They also support broadcasting, which allows for efficient computation on arrays of different shapes.
Python List: Python lists offer more general-purpose functionality and support a variety of operations such as appending, slicing, concatenating, and iterating over elements. However, they lack specialized numerical functions and operations available in NumPy.
Syntax:

NumPy Array: NumPy arrays are created using the numpy.array() function or by converting other data structures like lists or tuples using numpy.asarray(). Operations on NumPy arrays often use vectorized syntax, which allows for concise and efficient code.
Python List: Python lists are created using square brackets [ ] or by using the list() constructor. Operations on lists are typically performed using Python's built-in functions and methods or through list comprehensions.

In [1]:
'''3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

'''#Solution:-
Shape: The shape of an array gives the number of rows and columns it contains.

In this case, the array has 3 rows and 4 columns.
So, the shape of the array is (3, 4).
Size: The size of an array represents the total number of elements in the array.

In this case, the array has 3 rows and 4 columns, so it contains a total of 3 * 4 = 12 elements.
So, the size of the array is 12.
Dimension: The dimension of an array represents the number of axes (or directions) along which the array extends.

In this case, the array is a 2-dimensional array because it has both rows and columns.
So, the dimension of the array is 2.'''
import numpy as np

# Define the array using NumPy
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Find the shape, size, and dimension of the array
shape = arr.shape
size = arr.size
dimension = arr.ndim

# Print the results
print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)



Shape: (3, 4)
Size: 12
Dimension: 2


In [2]:
'''4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np

# Given array as a NumPy array
array_np = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Access the first row
first_row_np = array_np[0]

# Print the first row
print("First row (NumPy array):", first_row_np)


First row (NumPy array): [1 2 3 4]


In [3]:
'''5. How to you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np

# Given NumPy array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = array[2, 3]  # Third row (index 2), fourth column (index 3)

# Print the element
print("Element at the third row and fourth column:", element)



Element at the third row and fourth column: 12


In [4]:
'''6. Write code to extract all odd indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
import numpy as np

# Given NumPy array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = array[:, 1::2]  # Start from index 1, step by 2 along the columns

# Print the extracted elements
print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
'''7. How can you generate a random 3x3 matrix with values between 0 and 1?'''
import numpy as np
array=np.random.rand(3,3)
print(array)


[[0.09603009 0.72639857 0.18871546]
 [0.59883041 0.12116191 0.36396715]
 [0.84578966 0.08848141 0.25392764]]


#8. Describe the difference between np.ran^dm.rand and np.random.randn?
The np.random.rand and np.random.randn functions in NumPy are used to generate random numbers, but they have differences in terms of the distributions from which they sample.

np.random.rand:

This function generates random numbers from a uniform distribution over the interval [0, 1).
The generated values are uniformly distributed between 0 (inclusive) and 1 (exclusive).
You can specify the shape of the output array as arguments to this function.
Example usage: np.random.rand(3, 3) generates a 3x3 array with random values between 0 and 1.
np.random.randn:

This function generates random numbers from a standard normal distribution (Gaussian distribution) with mean 0 and standard deviation 1.
The generated values follow a bell-shaped curve centered around 0, with the majority of values falling close to the mean and fewer values farther away.
You can specify the shape of the output array as arguments to this function.
Example usage: np.random.randn(3, 3) generates a 3x3 array with random values sampled from a standard normal distribution.

In [8]:
'''9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''
'''You can increase the dimension of the given array by using NumPy's np.expand_dims() function. This function adds an extra dimension'''
import numpy as np

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_array = np.expand_dims(array, axis=0)

# Print the original and expanded arrays
print("Original array:")
print(array)
print("\nExpanded array:")
print(expanded_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [9]:
'''
10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]
'''
import numpy as np

# Given array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Transpose the array using numpy.transpose()
transposed_array = np.transpose(array)

# Print the transposed array
print("Transposed array:")
print(transposed_array)


Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [10]:
'''11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
1, Index wise multiplication
2, Matrix multiplication
3,Add both the matrix
4,Subtract matrix B from 
5, Divide Matrix B by A

'''
import numpy as np

# Define Matrix A2
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Define Matrix B2
B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A2 * B2
print("1. Index wise multiplication:")
print(index_wise_multiplication)

# 2. Matrix multiplication
matrix_multiplication = np.dot(A2, B2.T)  # Assuming you want to perform matrix multiplication and transpose B2
print("\n2. Matrix multiplication:")
print(matrix_multiplication)

# 3. Add both the matrices
addition = np.add(A2, B2)
print("\n3. Addition of matrices:")
print(addition)

# 4. Subtract matrix B from A
subtraction = np.subtract(A2, B2)
print("\n4. Subtraction of matrix B from A:")
print(subtraction)

# 5. Divide Matrix B by A
division = np.divide(B2, A2)
print("\n5. Division of Matrix B by A:")
print(division)


1. Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition of matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction of matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Division of Matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#12.  Which function in Numpy can be used to swap the byte order of an array?


import numpy as np

# Create an array with a specific byte order (little endian)
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
arr_swapped = arr.byteswap()

# Print the original and swapped arrays
print("Original array:", arr)
print("Swapped array:", arr_swapped)


Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


#13.  What is the significance of the np.linalg.inv function?
The np.linalg.inv function in NumPy is like a magic tool that helps you reverse the effects of a square magic square. Imagine you have a magic square (a special type of grid filled with numbers) that transforms other squares when you combine them. The np.linalg.inv function tells you how to undo that transformation, so you can get back to your original square.

Solving Linear Systems of Equations: It's like having a recipe to make a cake. If you know how to make a cake (the magic square), and someone gives you the final cake (a result), you can use the recipe in reverse to figure out what ingredients you need (solve for variables) to make that cake.

Eigenvalue and Eigenvector Computation: Imagine you have a special box that turns objects inside it when you close the lid. The np.linalg.inv function helps you figure out what you put inside the box originally by looking at how the objects have changed.

Determinant Computation: Think of the determinant as a special number that describes how much a magic square stretches or squishes things. The np.linalg.inv function helps you find this special number by undoing the stretching or squishing that the magic square does.

Orthogonalization and Projection: It's like having a pair of glasses that helps you see things from a different angle. The np.linalg.inv function helps you find out how to adjust the glasses to see things from the original angle again.

Regularization: Imagine you have a wonky table, and you need to put something underneath one of the legs to make it level. The np.linalg.inv function helps you figure out what to put under the leg to balance the table perfectly.
 

In [12]:
#14. What does the np.reshape function do, and how is it used?
'''The np.reshape function in NumPy is used to change the shape (dimensions) of an array while keeping the same data. It allows you to rearrange the elements of an array into a new shape without changing their values.

Here's what np.reshape does and how it's used:

Changing Array Shape: The primary purpose of np.reshape is to change the shape of an array. You can specify the new shape using a tuple of integers representing the desired dimensions.

Keeping Data Unchanged: When you reshape an array using np.reshape, the total number of elements in the reshaped array must remain the same as the original array. The function doesn't add or remove elements; it just rearranges them.

Row-Major Order: By default, NumPy uses row-major order (also known as C-style order) when reshaping arrays. This means that elements are read and written in rows (from left to right) before moving to the next row.'''
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 2 rows and 3 columns
reshaped_arr = np.reshape(arr, (2, 3))

# Print the original and reshaped arrays
print("Original array:")
print(arr)
print("\nReshaped array:")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [ ]:
#15. What is broadcasting in Numpy?
'''Broadcasting in NumPy is a powerful mechanism that allows arrays with different shapes to be combined and operated on together. It enables you to perform element-wise operations between arrays of different shapes without explicitly reshaping them to match.

Here's an overview of how broadcasting works in NumPy:

Implicit Expansion: Broadcasting occurs when NumPy automatically expands arrays with smaller shapes to match the shape of larger arrays during arithmetic operations.

Rules of Broadcasting:

If two arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its left side.
If the shape of the two arrays doesn't match along any dimension, the array with shape equal to 1 along that dimension is stretched to match the shape of the other array.
If neither array has a shape of 1 along a particular dimension, and their shapes don't match, NumPy raises a ValueError.
Benefits:

Simplifies Code: Broadcasting allows you to write concise and readable code by eliminating the need for explicit loops or reshaping operations.
Performance: Broadcasting is implemented in highly optimized C code within NumPy, leading to efficient computation.'''
import numpy as np

# Create two arrays with different shapes
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

# Perform element-wise addition using broadcasting
result = a + b

print(result)
